# Generated by Django 6.0.5 on 2026-05-12 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(choices=[('Tinggi', 'Tinggi'), ('Sedang', 'Sedang'), ('Rendah', 'Rendah')], max_length=10, verbose_name='Kategori Nilai')),
                ('prestasi', models.CharField(choices=[('Tinggi', 'Tinggi'), ('Sedang', 'Sedang'), ('Rendah', 'Rendah')], max_length=10, verbose_name='Kategori Prestasi')),
                ('penghasilan', models.CharField(choices=[('Rendah', 'Rendah'), ('Sedang', 'Sedang'), ('Tinggi', 'Tinggi')], max_length=10, verbose_name='Kategori Penghasilan')),
                ('kip', models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=10, verbose_name='Kepemilikan KIP')),
                ('hasil', models.CharField(choices=[('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], max_length=15, verbose_name='Hasil Klasifikasi')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Training',
                'verbose_name_plural': 'Dataset Training',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PenilaianBeasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_rata_rata', models.FloatField(verbose_name='Nilai Rata-rata Rapor')),
                ('ranking_kelas', models.PositiveIntegerField(verbose_name='Ranking Kelas')),
                ('persentase_hadir', models.FloatField(verbose_name='Persentase Kehadiran (%)')),
                ('kategori_nilai', models.CharField(blank=True, choices=[('Tinggi', 'Tinggi'), ('Sedang', 'Sedang'), ('Rendah', 'Rendah')], max_length=10, verbose_name='Kategori Nilai')),
                ('tingkat_prestasi', models.CharField(choices=[('Tinggi', 'Tinggi (Juara Nasional/Provinsi)'), ('Sedang', 'Sedang (Juara Kabupaten/Kota)'), ('Rendah', 'Rendah (Tidak Berprestasi)')], max_length=10, verbose_name='Tingkat Prestasi')),
                ('keaktifan_organisasi', models.CharField(choices=[('Aktif', 'Aktif'), ('Cukup', 'Cukup Aktif'), ('Tidak', 'Tidak Aktif')], max_length=10, verbose_name='Keaktifan Organisasi')),
                ('penghasilan_ortu', models.BigIntegerField(verbose_name='Penghasilan Orang Tua (Rp)')),
                ('jumlah_tanggungan', models.PositiveIntegerField(verbose_name='Jumlah Tanggungan Keluarga')),
                ('status_rumah', models.CharField(choices=[('Milik Sendiri', 'Milik Sendiri'), ('Sewa', 'Sewa/Kontrak'), ('Menumpang', 'Menumpang')], max_length=20, verbose_name='Status Rumah')),
                ('memiliki_kip', models.BooleanField(default=False, verbose_name='Memiliki KIP')),
                ('kategori_penghasilan', models.CharField(blank=True, choices=[('Rendah', 'Rendah (< Rp 2.000.000)'), ('Sedang', 'Sedang (Rp 2.000.000 - 4.000.000)'), ('Tinggi', 'Tinggi (> Rp 4.000.000)')], max_length=10, verbose_name='Kategori Penghasilan')),
                ('jarak_rumah', models.CharField(choices=[('Dekat', 'Dekat (< 5 km)'), ('Sedang', 'Sedang (5 - 15 km)'), ('Jauh', 'Jauh (> 15 km)')], max_length=10, verbose_name='Jarak Rumah ke Sekolah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Penilaian Beasiswa',
                'verbose_name_plural': 'Data Penilaian Beasiswa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=20, unique=True, verbose_name='NIS')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Siswa')),
                ('kelas', models.CharField(choices=[('X', 'Kelas X'), ('XI', 'Kelas XI'), ('XII', 'Kelas XII')], max_length=5, verbose_name='Kelas')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('no_hp', models.CharField(max_length=15, verbose_name='No. HP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diubah')),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Data Siswa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HasilSeleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_seleksi', models.CharField(choices=[('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], max_length=15, verbose_name='Status Seleksi')),
                ('entropy_awal', models.FloatField(verbose_name='Entropy Awal (S)')),
                ('root_node', models.CharField(max_length=50, verbose_name='Root Node Terpilih')),
                ('rules_json', models.TextField(verbose_name='Rules Keputusan (JSON)')),
                ('gain_info_json', models.TextField(verbose_name='Gain per Atribut (JSON)')),
                ('tanggal_seleksi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Seleksi')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan Tambahan')),
                ('penilaian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_seleksi', to='beasiswa.penilaianbeasiswa', verbose_name='Penilaian')),
            ],
            options={
                'verbose_name': 'Hasil Seleksi',
                'verbose_name_plural': 'Hasil Seleksi',
                'ordering': ['-tanggal_seleksi'],
            },
        ),
        migrations.AddField(
            model_name='penilaianbeasiswa',
            name='siswa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='beasiswa.siswa', verbose_name='Siswa'),
        ),
    ]
